<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\ProductCategory;
use App\Models\ProductTag;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        // Clean existing data
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('product_tag')->truncate();
        DB::table('products')->truncate();
        DB::table('product_categories')->truncate();
        DB::table('product_tags')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // ── Tags ─────────────────────────────────────────────────────────────
        $tagDefs = [
            'Satellite',
            'CATV',
            'HD Ready',
            '4K',
            'KU Band',
            'C Band',
            'DVB-T2',
            'Indoor',
            'Power Pass',
            'Digital',
            'Fiber Optic',
            'Wall Mount',
        ];

        $tags = [];
        foreach ($tagDefs as $name) {
            $tags[$name] = ProductTag::create([
                'name'      => $name,
                'slug'      => Str::slug($name),
                'is_active' => true,
            ]);
        }

        // ── Categories ───────────────────────────────────────────────────────
        $categoryDefs = [
            'LNBF'                            => 'Low Noise Block Feed converters for satellite dish installations.',
            'Signal Amplifiers'               => 'Amplifiers for boosting TV, satellite, and cable TV signals.',
            'Splitters & Signal Distribution' => 'Splitters and distribution components for satellite and CATV signals.',
            'Satellite Test Equipment'        => 'Tools and meters for satellite dish alignment and signal testing.',
            'TV Antennas'                     => 'Indoor and outdoor antennas for terrestrial TV reception.',
            'RF Modulators & Converters'      => 'Devices that convert AV/HDMI signals to RF for coaxial distribution.',
            'TV Mounts & Accessories'         => 'Wall brackets, stands, and accessories for mounting TV screens.',
            'Power Backup Equipment'          => 'Inverters and UPS systems for stable backup power supply.',
            'CATV & Fiber Equipment'          => 'Optical receivers, nodes, and equipment for CATV and fiber networks.',
            'Signal Distribution Accessories' => 'Power inserters and accessories for signal distribution systems.',
            'Satellite Signal Distribution'   => 'Multiswitches and systems for distributing satellite signals.',
        ];

        $cats = [];
        foreach ($categoryDefs as $name => $desc) {
            $cats[$name] = ProductCategory::create([
                'name'        => $name,
                'slug'        => Str::slug($name),
                'description' => $desc,
                'is_active'   => true,
            ]);
        }

        // ── Products ─────────────────────────────────────────────────────────
        // [img, title, brand, sku, category, description, retail, discounted, qty, tags[]]
        $products = [
            [
                'img'         => 'Eurostar - ESS - 4 5 - 2400 MHZ Spliter .png',
                'title'       => '4-Way Satellite Splitter (Power Pass)',
                'brand'       => 'Eurostar ESS-4',
                'sku'         => 'EUR-ESS-4',
                'category'    => 'Splitters & Signal Distribution',
                'description' => 'High-performance 4-way splitter supporting 5–2400 MHz frequency range with power passing capability. Ideal for distributing satellite signals to multiple receivers while maintaining signal quality.',
                'retail'      => 1800.00,
                'discounted'  => 1550.00,
                'qty'         => 85,
                'tags'        => ['Satellite', 'Power Pass', 'Digital'],
            ],
            [
                'img'         => 'AC, DC, SOLAR - Hybrid Amplifier - 80 MHZ.png',
                'title'       => 'Hybrid Signal Amplifier 860 MHz (AC/DC/Solar Compatible)',
                'brand'       => 'Generic Hybrid Amp',
                'sku'         => 'GEN-HYB-860',
                'category'    => 'Signal Amplifiers',
                'description' => 'Professional CATV/satellite hybrid amplifier with dual output and monitoring support. Operates using AC, DC, or solar power. Designed for boosting weak TV or satellite signals in residential or commercial installations.',
                'retail'      => 7500.00,
                'discounted'  => 6800.00,
                'qty'         => 40,
                'tags'        => ['CATV', 'Satellite', 'Digital'],
            ],
            [
                'img'         => 'DBC Technologies.png',
                'title'       => 'Digital Satellite Signal Finder Meter',
                'brand'       => 'DBC DSF-999-BC',
                'sku'         => 'DBC-DSF-999',
                'category'    => 'Satellite Test Equipment',
                'description' => 'Portable satellite signal finder with LCD screen, 950–2150 MHz support, USB interface, rechargeable battery, and multi-standard demodulation. Helps installers align dishes quickly and accurately.',
                'retail'      => 12500.00,
                'discounted'  => 11000.00,
                'qty'         => 25,
                'tags'        => ['Satellite', 'Digital'],
            ],
            [
                'img'         => 'DG tech - Built in Booster 5G Elimination Filter.png',
                'title'       => 'Booster LNBF with Built-in 5G Filter',
                'brand'       => 'DGTech DT-999HD',
                'sku'         => 'DGT-DT-999HD',
                'category'    => 'LNBF',
                'description' => 'High-gain universal KU LNBF with integrated 5G interference filter. Supports Full HD & 4K signals with low noise performance for stable satellite reception.',
                'retail'      => 3200.00,
                'discounted'  => 2800.00,
                'qty'         => 60,
                'tags'        => ['Satellite', 'KU Band', 'HD Ready', '4K'],
            ],
            [
                'img'         => 'Eurostar - 3 RO Genaeration LNBF - LP-9.png',
                'title'       => 'KU Band Prime Focus LNBF',
                'brand'       => 'Eurostar LP-9',
                'sku'         => 'EUR-LP-9',
                'category'    => 'LNBF',
                'description' => 'Premium KU-band LNBF designed for prime-focus dishes. Provides high signal stability and excellent digital reception quality. Suitable for residential and commercial satellite installations.',
                'retail'      => 2800.00,
                'discounted'  => 2450.00,
                'qty'         => 75,
                'tags'        => ['Satellite', 'KU Band', 'Digital'],
            ],
            [
                'img'         => 'Eurostar - 3RO Genaeration LNBF.png',
                'title'       => 'Twin Universal KU LNBF (0.5 dB)',
                'brand'       => 'Eurostar T2 Slim+HD',
                'sku'         => 'EUR-T2-SLIM',
                'category'    => 'LNBF',
                'description' => 'Twin-output universal LNBF allowing connection of two receivers. HD-ready with low noise figure for clear satellite TV reception.',
                'retail'      => 3500.00,
                'discounted'  => 3100.00,
                'qty'         => 65,
                'tags'        => ['Satellite', 'KU Band', 'HD Ready'],
            ],
            [
                'img'         => 'Eurostar - 4 way splitter - All Ports Powers Passing .png',
                'title'       => '4-Way Power Passing Splitter',
                'brand'       => 'Eurostar EPD-14 Plus',
                'sku'         => 'EUR-EPD-14P',
                'category'    => 'Splitters & Signal Distribution',
                'description' => 'Heavy-duty 4-way splitter supporting 950–2500 MHz with all-port power passing. Ideal for multi-room satellite distribution systems.',
                'retail'      => 2200.00,
                'discounted'  => 1950.00,
                'qty'         => 90,
                'tags'        => ['Satellite', 'Power Pass', 'Digital'],
            ],
            [
                'img'         => 'Eurostar - Digital Indoor TV Antena.png',
                'title'       => 'Digital Indoor TV Antenna High Gain DVB-T2',
                'brand'       => 'Eurostar T-55',
                'sku'         => 'EUR-T-55',
                'category'    => 'TV Antennas',
                'description' => 'Compact high-gain indoor TV antenna compatible with DVB-T/T2 HD signals. Adjustable rods improve reception quality in urban homes.',
                'retail'      => 1500.00,
                'discounted'  => 1250.00,
                'qty'         => 120,
                'tags'        => ['DVB-T2', 'Indoor', 'HD Ready', 'Digital'],
            ],
            [
                'img'         => 'Eurostar - ES QP4 - HD.png',
                'title'       => 'Quad Universal KU LNBF (HD 0.5 dB)',
                'brand'       => 'Eurostar ES-QP4',
                'sku'         => 'EUR-ES-QP4',
                'category'    => 'LNBF',
                'description' => 'Quad-output universal LNBF for connecting up to four receivers. HD-ready design with low noise figure ensures stable signal performance.',
                'retail'      => 4200.00,
                'discounted'  => 3800.00,
                'qty'         => 50,
                'tags'        => ['Satellite', 'KU Band', 'HD Ready'],
            ],
            [
                'img'         => 'ARISAT - Universal LNB.png',
                'title'       => 'Universal KU LNBF High Gain',
                'brand'       => 'Arisat AT-1 HD',
                'sku'         => 'ARI-AT1-HD',
                'category'    => 'LNBF',
                'description' => 'High-gain universal KU LNBF designed for Full HD digital reception. Reliable performance for home satellite installations.',
                'retail'      => 2500.00,
                'discounted'  => 2100.00,
                'qty'         => 100,
                'tags'        => ['Satellite', 'KU Band', 'HD Ready', 'Digital'],
            ],
            [
                'img'         => 'Global - CATV Single Amplifier.png',
                'title'       => 'CATV Signal Amplifier Multi-Output',
                'brand'       => 'Global GCA-208G',
                'sku'         => 'GLB-GCA-208G',
                'category'    => 'Signal Amplifiers',
                'description' => 'Multi-output CATV signal amplifier designed to boost cable TV signals across multiple rooms. Stable amplification with low noise for residential and commercial distribution networks.',
                'retail'      => 5500.00,
                'discounted'  => 4900.00,
                'qty'         => 45,
                'tags'        => ['CATV', 'Digital'],
            ],
            [
                'img'         => 'Gulf Star - Digital C Band Twin LNBF.png',
                'title'       => 'C-Band Twin LNBF Digital Receiver',
                'brand'       => 'Gulf Star C-Band Twin',
                'sku'         => 'GUL-CB-TWIN',
                'category'    => 'LNBF',
                'description' => 'Digital C-band twin LNBF with dual output support. Designed for satellite dishes receiving C-band frequencies with stable signal performance and low noise figure.',
                'retail'      => 4800.00,
                'discounted'  => 4200.00,
                'qty'         => 35,
                'tags'        => ['Satellite', 'C Band', 'Digital'],
            ],
            [
                'img'         => 'HDMI+AV to RF Modulator.png',
                'title'       => 'HDMI & AV to RF Modulator',
                'brand'       => 'Eurostar ES-500',
                'sku'         => 'EUR-ES-500',
                'category'    => 'RF Modulators & Converters',
                'description' => 'Converts HDMI or AV signals into RF output for distribution through coaxial cable networks. Ideal for hotels, apartments, and CCTV channel distribution.',
                'retail'      => 8500.00,
                'discounted'  => 7800.00,
                'qty'         => 30,
                'tags'        => ['Digital', 'CATV'],
            ],
            [
                'img'         => 'Hybrid Amplifier - 80 MHZ - United System.png',
                'title'       => 'Hybrid Signal Amplifier 860 MHz Dual Output',
                'brand'       => 'United System Hybrid 860 MHz',
                'sku'         => 'UNS-HYB-860D',
                'category'    => 'Signal Amplifiers',
                'description' => '860 MHz hybrid CATV amplifier with dual output and monitoring support. Improves signal strength across long cable runs or large building networks.',
                'retail'      => 7200.00,
                'discounted'  => 6500.00,
                'qty'         => 40,
                'tags'        => ['CATV', 'Digital'],
            ],
            [
                'img'         => 'Hybrid Amplifier - 900 MHZ.png',
                'title'       => 'Hybrid Signal Amplifier 900 MHz HD Ready',
                'brand'       => 'Generic Hybrid 900 MHz',
                'sku'         => 'GEN-HYB-900',
                'category'    => 'Signal Amplifiers',
                'description' => '900 MHz hybrid amplifier designed to enhance cable or antenna signals with HD compatibility. Suitable for indoor distribution networks.',
                'retail'      => 6800.00,
                'discounted'  => 6000.00,
                'qty'         => 38,
                'tags'        => ['CATV', 'HD Ready', 'Digital'],
            ],
            [
                'img'         => 'Indoor Broad Amplifier - AD 540 Plus.png',
                'title'       => 'Indoor Broadband Signal Amplifier',
                'brand'       => 'Fagor AD-540 Plus',
                'sku'         => 'FAG-AD-540P',
                'category'    => 'Signal Amplifiers',
                'description' => 'Compact indoor broadband amplifier with multiple outputs. Enhances TV signal quality in homes with weak reception or long cable routing.',
                'retail'      => 4500.00,
                'discounted'  => 3900.00,
                'qty'         => 55,
                'tags'        => ['Indoor', 'CATV', 'Digital'],
            ],
            [
                'img'         => 'Eurostar - ESS - 6 5 - 2400 MHZ Spliter.png',
                'title'       => '6-Way Satellite Splitter Power Pass',
                'brand'       => 'Eurostar ESS-6',
                'sku'         => 'EUR-ESS-6',
                'category'    => 'Splitters & Signal Distribution',
                'description' => 'Heavy-duty 6-way splitter supporting 5–2400 MHz frequency range with power passing. Ideal for multi-room satellite installations.',
                'retail'      => 2800.00,
                'discounted'  => 2400.00,
                'qty'         => 70,
                'tags'        => ['Satellite', 'Power Pass', 'Digital'],
            ],
            [
                'img'         => 'Eurostar - Universal Twin LNBF - ES T2 HD 4K .png',
                'title'       => 'Universal Twin KU LNBF HD 4K',
                'brand'       => 'Eurostar ES-T2 HD 4K',
                'sku'         => 'EUR-T2-4K',
                'category'    => 'LNBF',
                'description' => 'Twin-output universal KU LNBF compatible with HD and 4K satellite signals. Allows connection of two receivers simultaneously with low noise performance.',
                'retail'      => 4000.00,
                'discounted'  => 3500.00,
                'qty'         => 60,
                'tags'        => ['Satellite', 'KU Band', 'HD Ready', '4K'],
            ],
            [
                'img'         => 'Eurostar- LNBF Single Solution-HD Signal Compatible.png',
                'title'       => 'Universal KU Single LNBF HD Compatible',
                'brand'       => 'Eurostar ES-21 Gold+',
                'sku'         => 'EUR-ES21-GLD',
                'category'    => 'LNBF',
                'description' => 'Single-output KU LNBF with anti-WiMAX interference protection. Designed for strong HD signal reception with stable performance.',
                'retail'      => 2200.00,
                'discounted'  => 1900.00,
                'qty'         => 110,
                'tags'        => ['Satellite', 'KU Band', 'HD Ready'],
            ],
            [
                'img'         => 'Eurostar- Satalitte Finder.png',
                'title'       => 'Analog Satellite Signal Finder Meter',
                'brand'       => 'Eurostar Satellite Finder',
                'sku'         => 'EUR-SAT-FIND',
                'category'    => 'Satellite Test Equipment',
                'description' => 'Compact satellite signal finder used for dish alignment. Helps installers quickly locate satellite signal strength for accurate setup.',
                'retail'      => 3500.00,
                'discounted'  => 2900.00,
                'qty'         => 45,
                'tags'        => ['Satellite'],
            ],
            [
                'img'         => 'Inverto - Selected Single 40mm LNB.png',
                'title'       => 'Premium Single Universal KU LNBF 40mm',
                'brand'       => 'Inverto Black Premium Single',
                'sku'         => 'INV-BLK-40MM',
                'category'    => 'LNBF',
                'description' => 'High-quality single universal KU LNBF with low noise design and 40mm feed support. Suitable for HD satellite reception with stable signal performance.',
                'retail'      => 5500.00,
                'discounted'  => 4800.00,
                'qty'         => 30,
                'tags'        => ['Satellite', 'KU Band', 'HD Ready'],
            ],
            [
                'img'         => "LEO STAR - LCD,LED,PLASMA Wall Bracket - 14''-37'' LCD Screen.png",
                'title'       => 'Swivel TV Wall Mount Bracket 14–37 inch',
                'brand'       => 'LeoStar LS-WBM-9042',
                'sku'         => 'LEO-WBM-9042',
                'category'    => 'TV Mounts & Accessories',
                'description' => 'Adjustable LCD/LED wall bracket with swivel arm design. Supports screens 14–37 inches with strong steel construction and flexible viewing angles.',
                'retail'      => 3200.00,
                'discounted'  => 2700.00,
                'qty'         => 80,
                'tags'        => ['Wall Mount', 'Indoor'],
            ],
            [
                'img'         => 'LEO STAR - LCD,LED,PLASMA Wall Bracket Fixed Style.png',
                'title'       => 'Fixed TV Wall Mount Bracket 19–42 inch',
                'brand'       => 'LeoStar LS-WBT-9010',
                'sku'         => 'LEO-WBT-9010',
                'category'    => 'TV Mounts & Accessories',
                'description' => 'Fixed-style wall mount bracket for LED/LCD TVs. Strong metal construction with easy installation support. Ideal for home entertainment setups.',
                'retail'      => 2500.00,
                'discounted'  => 2100.00,
                'qty'         => 95,
                'tags'        => ['Wall Mount', 'Indoor'],
            ],
            [
                'img'         => 'Leo Star - LS-DS-9066.png',
                'title'       => 'Tempered Glass TV Shelf Stand',
                'brand'       => 'LeoStar LS-DS-9066',
                'sku'         => 'LEO-DS-9066',
                'category'    => 'TV Mounts & Accessories',
                'description' => 'Wall-mounted tempered glass shelf designed for receivers, set-top boxes, or DVD players. Compact and stylish design for modern home setups.',
                'retail'      => 1800.00,
                'discounted'  => 1500.00,
                'qty'         => 70,
                'tags'        => ['Wall Mount', 'Indoor'],
            ],
            [
                'img'         => 'Microtek - Smart Hybrid.png',
                'title'       => 'Smart Hybrid Pure Sinewave Inverter 1075VA',
                'brand'       => 'Microtek Smart Hybrid 1075VA',
                'sku'         => 'MIC-SH-1075',
                'category'    => 'Power Backup Equipment',
                'description' => 'True sinewave inverter with smart hybrid technology. Provides stable backup power for home electronics with efficient battery usage.',
                'retail'      => 28500.00,
                'discounted'  => 25000.00,
                'qty'         => 20,
                'tags'        => ['Digital'],
            ],
            [
                'img'         => 'Multilink Network - Optical Receiver (Node).png',
                'title'       => 'Optical Receiver Node 1000 MHz Dual Output',
                'brand'       => 'Multilink Network Optical Receiver',
                'sku'         => 'MLN-OPT-1000',
                'category'    => 'CATV & Fiber Equipment',
                'description' => 'Optical receiver node with dual output and test point. Designed for CATV fiber networks to convert optical signal to RF output efficiently.',
                'retail'      => 18500.00,
                'discounted'  => 16500.00,
                'qty'         => 15,
                'tags'        => ['Fiber Optic', 'CATV', 'Digital'],
            ],
            [
                'img'         => 'NOVATECH - 3 Way Supplier - 5-1000 MHZ.png',
                'title'       => '3-Way Signal Splitter Power Pass 5–1000 MHz',
                'brand'       => 'Novatech 3SP 6P',
                'sku'         => 'NOV-3SP-6P',
                'category'    => 'Splitters & Signal Distribution',
                'description' => 'Durable 3-way splitter supporting digital CATV signals with power pass capability. Ideal for distributing TV signal to multiple receivers.',
                'retail'      => 1600.00,
                'discounted'  => 1350.00,
                'qty'         => 100,
                'tags'        => ['CATV', 'Power Pass', 'Digital'],
            ],
            [
                'img'         => 'NOVATECH - Power Insetter -40-860 MHZ.png',
                'title'       => 'Power Inserter 40–860 MHz Digital',
                'brand'       => 'Novatech Power Inserter',
                'sku'         => 'NOV-PWR-INS',
                'category'    => 'Signal Distribution Accessories',
                'description' => 'Power inserter designed to supply power to amplifiers or LNBFs via coaxial cable. Supports 40–860 MHz digital signal range.',
                'retail'      => 2200.00,
                'discounted'  => 1900.00,
                'qty'         => 55,
                'tags'        => ['CATV', 'Digital'],
            ],
            [
                'img'         => 'PAUXIS Satellite.png',
                'title'       => 'Universal C/KU Band Satellite LNBF',
                'brand'       => 'Pauxis Universal C/KU LNBF',
                'sku'         => 'PAX-CKU-LNBF',
                'category'    => 'LNBF',
                'description' => 'Universal satellite LNBF supporting C-band and KU-band signals. Designed for flexible satellite dish setups with reliable reception.',
                'retail'      => 3800.00,
                'discounted'  => 3300.00,
                'qty'         => 45,
                'tags'        => ['Satellite', 'C Band', 'KU Band'],
            ],
            [
                'img'         => 'Sharp Vision - AS 1313 - Hybrid Amplifier .png',
                'title'       => 'Hybrid Signal Amplifier 900 MHz Dual Output',
                'brand'       => 'Sharp Vision AS-1313',
                'sku'         => 'SHV-AS-1313',
                'category'    => 'Signal Amplifiers',
                'description' => 'High-output hybrid amplifier with dual output support and power pass capability. Designed for cable TV network signal boosting.',
                'retail'      => 7800.00,
                'discounted'  => 7000.00,
                'qty'         => 35,
                'tags'        => ['CATV', 'Power Pass', 'Digital'],
            ],
            [
                'img'         => 'Sharp Vision - Battery Node - OX 722 B.png',
                'title'       => 'FTTH Battery Backup Node – Dual RF Output',
                'brand'       => 'Sharp Vision OX 722 B',
                'sku'         => 'SHV-OX-722B',
                'category'    => 'CATV & Fiber Equipment',
                'description' => 'DC FTTH battery backup node with built-in rechargeable battery. Provides up to 20 hours backup power with dual high RF output. Designed for CATV and fiber network signal stability.',
                'retail'      => 22000.00,
                'discounted'  => 19500.00,
                'qty'         => 18,
                'tags'        => ['Fiber Optic', 'CATV', 'Digital'],
            ],
            [
                'img'         => 'Sharp Vision - Battery Node - OX 724 B.png',
                'title'       => 'FTTH Battery Backup Node – Quad RF Output',
                'brand'       => 'Sharp Vision OX 724 B',
                'sku'         => 'SHV-OX-724B',
                'category'    => 'CATV & Fiber Equipment',
                'description' => 'High-capacity battery node with built-in charger and quad RF output. Supports FTTH network installations with extended backup time and stable signal delivery.',
                'retail'      => 26000.00,
                'discounted'  => 23000.00,
                'qty'         => 15,
                'tags'        => ['Fiber Optic', 'CATV', 'Digital'],
            ],
            [
                'img'         => 'Televes Modulator.png',
                'title'       => 'RF TV Signal Modulator',
                'brand'       => 'Televes RF Modulator',
                'sku'         => 'TEL-RF-MOD',
                'category'    => 'RF Modulators & Converters',
                'description' => 'Converts AV signals into RF output for distribution via coaxial networks. Ideal for hotels, apartments, CCTV channel distribution, and multi-room installations.',
                'retail'      => 9500.00,
                'discounted'  => 8500.00,
                'qty'         => 25,
                'tags'        => ['CATV', 'Digital'],
            ],
            [
                'img'         => 'Triax Multiswitch.png',
                'title'       => 'Satellite Multiswitch Distribution Unit',
                'brand'       => 'Triax Multiswitch',
                'sku'         => 'TRX-MSWITCH',
                'category'    => 'Satellite Signal Distribution',
                'description' => 'Professional multiswitch system for distributing satellite signal to multiple receivers from a single dish setup. Suitable for apartments, hotels, and commercial satellite networks.',
                'retail'      => 14500.00,
                'discounted'  => 12800.00,
                'qty'         => 22,
                'tags'        => ['Satellite', 'Digital'],
            ],
        ];

        foreach ($products as $data) {
            $slug = Str::slug($data['title']);
            $uniqueSlug = $slug;
            $counter = 1;
            while (Product::where('slug', $uniqueSlug)->exists()) {
                $uniqueSlug = $slug . '-' . $counter++;
            }

            $product = Product::create([
                'title'               => $data['title'],
                'slug'                => $uniqueSlug,
                'brand'               => $data['brand'],
                'meta_title'          => $data['title'],
                'meta_description'    => $data['description'],
                'meta_keyword'        => Str::slug($data['brand'], ','),
                'product_category_id' => $cats[$data['category']]->id,
                'description'         => '<p>' . $data['description'] . '</p>',
                'main_img'            => 'assets/img/product/566746376.jpg',
                'other_img'           => null,
                'product_code'        => $data['sku'],
                'retail_price'        => $data['retail'],
                'discounted_price'    => $data['discounted'],
                'qty'                 => $data['qty'],
                'product_status'      => 'in_stock',
                'is_active'           => true,
            ]);

            $tagIds = collect($data['tags'])->map(fn ($name) => $tags[$name]->id)->toArray();
            $product->tags()->sync($tagIds);
        }
    }
}
